### ISSUE TITLE
Bigin Crash

### ISSUE THREAD

**Issue by deep-ink-ventures** [deep-ink-ventures/genesis-dao-node#90]
The database may need to store the token issuance differently.

The following input for token issuance (`9,393,939,390,000,000,000`) crashed the bigint limit of `9,223,372,036,854,775,808`.

That's 900 Mio Dot-Units which is not totally off for token issuance. 

When this happens the entire service breaks.
```
17/04/2023, 16:42:04 | Block not executable. number: 16784 \| hash: 0xc65fa28446e46d41cef14a942eb85382d3feecd5907024e697d00bc79a0d61f9 | div-gen-backend-listener
-- | -- | --
17/04/2023, 16:42:04 | Traceback (most recent call last): | div-gen-backend-listener
17/04/2023, 16:42:04 | File "/venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute | div-gen-backend-listener
17/04/2023, 16:42:04 | return self.cursor.execute(sql, params) | div-gen-backend-listener
17/04/2023, 16:42:04 | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ | div-gen-backend-listener
17/04/2023, 16:42:04 | psycopg2.errors.NumericValueOutOfRange: bigint out of range | div-gen-backend-listener
17/04/2023, 16:42:04 | The above exception was the direct cause of the following exception: | div-gen-backend-listener
17/04/2023, 16:42:04 | Traceback (most recent call last): | div-gen-backend-listener
17/04/2023, 16:42:04 | File "/usr/src/app/core/event_handler.py", line 320, in execute_actions | div-gen-backend-listener
17/04/2023, 16:42:04 | block_action(block=block) | div-gen-backend-listener
17/04/2023, 16:42:04 | File "/usr/src/app/core/event_handler.py", line 165, in _create_assets | div-gen-backend-listener
17/04/2023, 16:42:04 | for asset_holding_obj, asset in zip(asset_holdings, models.Asset.objects.bulk_create(assets)): | div-gen-backend-listener
17/04/2023, 16:42:04 | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ | div-gen-backend-listener
17/04/2023, 16:42:04 | File "/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 85, in manager_method | div-gen-backend-listener
17/04/2023, 16:42:04 | return getattr(self.get_queryset(), name)(*args, **kwargs) | div-gen-backend-listener
17/04/2023, 16:42:04 | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ | div-gen-backend-listener
17/04/2023, 16:42:04 | File "/venv/lib/python3.11/site-packages/django/db/models/query.py", line 799, in bulk_create | div-gen-backend-listener
17/04/2023, 16:42:04 | returned_columns = self._batched_insert( | div-gen-backend-listener
17/04/2023, 16:42:04 | ^^^^^^^^^^^^^^^^^^^^^ | div-gen-backend-listener
17/04/2023, 16:42:04 | File "/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1817, in _batched_insert | div-gen-backend-listener
17/04/2023, 16:42:04 | self._insert( | div-gen-backend-listener
17/04/2023, 16:42:04 | File "/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1791, in _insert | div-gen-backend-listener
17/04/2023, 16:42:04 | return query.get_compiler(using=using).execute_sql(returning_fields) | div-gen-backend-listener
17/04/2023, 16:42:04 | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ | div-gen-backend-listener
17/04/2023, 16:42:04 | File "/venv/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1660, in execute_sql | div-gen-backend-listener
17/04/2023, 16:42:04 | cursor.execute(sql, params) | div-gen-backend-listener
17/04/2023, 16:42:04 | File "/venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute | div-gen-backend-listener
17/04/2023, 16:42:04 | return self._execute_with_wrappers( | div-gen-backend-listener
17/04/2023, 16:42:04 | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ | div-gen-backend-listener
17/04/2023, 16:42:04 | File "/venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers | div-gen-backend-listener
17/04/2023, 16:42:04 | return executor(sql, params, many, context) | div-gen-backend-listener
17/04/2023, 16:42:04 | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ | div-gen-backend-listener
17/04/2023, 16:42:04 | File "/venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute | div-gen-backend-listener
17/04/2023, 16:42:04 | with self.db.wrap_database_errors: | div-gen-backend-listener
17/04/2023, 16:42:04 | File "/venv/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__ | div-gen-backend-listener
17/04/2023, 16:42:04 | raise dj_exc_value.with_traceback(traceback) from exc_value | div-gen-backend-listener
17/04/2023, 16:42:04 | File "/venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute | div-gen-backend-listener
17/04/2023, 16:42:04 | return self.cursor.execute(sql, params) | div-gen-backend-listener
17/04/2023, 16:42:04 | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ | div-gen-backend-listener
17/04/2023, 16:42:04 | django.db.utils.DataError: bigint out of range | div-gen-backend-listener
17/04/2023, 16:42:04 | During handling of the above exception, another exception occurred: | div-gen-backend-listener
17/04/2023, 16:42:04 | Traceback (most recent call last): | div-gen-backend-listener
17/04/2023, 16:42:04 | File "/usr/src/app/core/substrate.py", line 589, in listen | div-gen-backend-listener
17/04/2023, 16:42:04 | substrate_event_handler.execute_actions(last_block) | div-gen-backend-listener
17/04/2023, 16:42:04 | File "/usr/local/lib/python3.11/contextlib.py", line 81, in inner | div-gen-backend-listener
17/04/2023, 16:42:04 | return func(*args, **kwds) | div-gen-backend-listener
17/04/2023, 16:42:04 | ^^^^^^^^^^^^^^^^^^^ | div-gen-backend-listener
17/04/2023, 16:42:04 | File "/usr/src/app/core/event_handler.py", line 328, in execute_actions | div-gen-backend-listener
17/04/2023, 16:42:04 | raise ParseBlockException(msg) | div-gen-backend-listener
17/04/2023, 16:42:04 | core.event_handler.ParseBlockException: Unexpected error while parsing Block #16784. | div-gen-backend-listener
17/04/2023, 16:42:04 | DB and chain are out of sync! Recreating DB... | div-gen-backend-listener
17/04/2023, 16:42:04 | cursor.execute(sql, params) | div-gen-backend-listener
17/04/2023, 16:42:04 | File "/venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute | div-gen-backend-listener
17/04/2023, 16:42:04 | return self._execute_with_wrappers( | div-gen-backend-listener
17/04/2023, 16:42:04 | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ | div-gen-backend-listener
17/04/2023, 16:42:04 | File "/venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers | div-gen-backend-listener
17/04/2023, 16:42:04 | return executor(sql, params, many, context) | div-gen-backend-listener
17/04/2023, 16:42:04 | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ | div-gen-backend-listener
17/04/2023, 16:42:04 | File "/venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute | div-gen-backend-listener
17/04/2023, 16:42:04 | with self.db.wrap_database_errors: | div-gen-backend-listener
17/04/2023, 16:42:04 | File "/venv/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__ | div-gen-backend-listener
17/04/2023, 16:42:04 | raise dj_exc_value.with_traceback(traceback) from exc_value | div-gen-backend-listener
17/04/2023, 16:42:04 | File "/venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute | div-gen-backend-listener
17/04/2023, 16:42:04 | return self.cursor.execute(sql, params) | div-gen-backend-listener
17/04/2023, 16:42:04 | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ | div-gen-backend-listener
17/04/2023, 16:42:04 | django.db.utils.DataError: bigint out of range
```

**Comment by Shirku** [comment]
https://github.com/deep-ink-ventures/genesis-dao-service/commit/758219d637fe7ffc15da17df0c9dad084121f8f1
